### ISSUE TITLE
마인드 셋

### ISSUE THREAD

**Issue by wonyongChoi05** [kimdoyoep/TIL-frontend#1]
방학했는데 왜 공부량이 더 줄어들지??????
마인드 **fucking** 다시 리셋해
지금 너무 안일해~
남은 방학 열정가지고 꾸준히 열심히 하도록 해보자.

> **큰 목표를 이루고 싶으면 허락을 구하지 마라. – 미상**

**Comment by kimdoyoep** [comment]
확실히 지금 너무 안일하긴해. 솔직히 원용이 너도 이제 곧 서울 올라가니까 심리적으로 많이 두려우면서 혼란스럽고 방학이라서 많이
프리해졌다. 빨리 마인드 리셋하고 빡공모드 들어가야지 계속 잡아줘서 고맘다 너무 큰 도움이 된다. 화이팅👊

**Comment by wonyongChoi05** [comment]
올해 [회고록](https://developer-nyong.tistory.com/13)인데 시간 날 때 읽어 봐봐, 너도 시간나면 쓰면서 2023년은 어떻게 살아갈지 고민해봐

내가 서울 올라간다고 니 마인드가 말랑해진다? 이건 ㅈ된거야 자기파악 빠르게 끝내고 가치관 확립하자!!

**Comment by kimdoyoep** [comment]
알지 근데 알면서도 마인드가 잘 안잡힌다. but 저번에 3주 야무지게 쉬면서 배웠다. 마인드가 말랑해지면 그에 따른 리스크는 감당하기
힘들다는 거 그래서 이번에는 쉽게 풀어지지 않을 거다.

**Comment by kimdoyoep** [comment]
열심히 따라갈게 옆에서 응원해줘라

**Comment by wonyongChoi05** [comment]
당연하지 올해도 화이팅^^

**Comment by wonyongChoi05** [comment]
아 그리고 교회는 못갈것 같다 연락 안해도 댐^^

**Comment by kimdoyoep** [comment]
화이팅~!

**Comment by kimdoyoep** [comment]
아하 알겠스~ 굿나잇!
